---
- name: Checkdiff
  hosts: all
  gather_facts: false

  tasks:
  - name: Check diff
    cisco.ios.ios_config:
      diff_against: startup
    register: output
  - name: Print out
    ansible.builtin.debug:
      msg: "{{output}}"
