---
- name: VRRP Config
  cisco.ios.ios_config:
    lines:
      - vrrp {{item}} priority 110
    parents: interface vlan{{item}}
  loop: "{{  outer_item | map(attribute='root_vlan') | string | split(',') }}"
  when: inventory_hostname == outer_item.device