---
- name: VRRP Config
  cisco.ios.ios_config:
    lines:
      - vrrp {{item}} priority 110
    parents: interface vlan{{item}}
  loop: "{{  STP_root | map(attribute='root_vlan') | string | split(',') | list }}"
  when: inventory_hostname == outer_item.device