---
- name: Config VRRP
  cisco.ios.ios_config:
    lines:
      - vrrp {{item.id}} ip 192.168.{{item.id}}{{default_gateway}}
      - vrrp {{item.id}} preempt
      - no shut
    parents: interface vlan{{item.id}}
  loop: "{{vlan_info}}"


- include_tasks: inner.yml
  loop: "{{STP_root}}"
  when: inventory_hostname == item.device
