---
- name: Config VRRP
  cisco.ios.ios_config:
    lines:
      - vrrp {{item.id}} ip 192.168.{{item.id}}{{default_gateway}}
      - vrrp {{item.id}} preempt
      - no shut
    parents: interface vlan{{item.id}}
  loop: "{{vlan_info}}"

- name: Config VRRP priority
  cisco.ios.ios_config:
    lines:
      - vrrp {{master_vlan}} priority 110
    parents: interface vlan{{master_vlan}}
  loop: "{{ STP_root }}"
  vars:
    master_vlan: "{{ item | map(attribute='root_vlan') | string | split(',') }}"
  when: inventory_hostname == item.device
