---
- name: Config VRRP
  cisco.ios.ios_config:
    lines:
      - vrrp {{item.id}} ip 192.168.{{item.id}}{{default_gateway}}
      - vrrp {{item.id}} preempt
      - no shut
    parents: interface vlan{{item.id}}
  loop: "{{vlan_info}}"


- name: VRRP Prioritize
  cisco.ios.ios_config:
    lines:
      - vrrp {{item.vlan}} priority 110
    parents: interface vlan{{item.vlan}}
  loop: "{{ VRRP }}"
  when: inventory_hostname == VRRP.device
