---
- name: Backup the network device
  hosts: all
  gather_facts: false

  tasks:
  - name: Backup the Cisco Devices
    cisco.ios.ios_config:
      backup: true
      backup_options:
        dir_path: ./BackupFiles
     
