---
- name: Configure Access Port
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{item.name}}"
        mode: access
        access:
          vlan: "{{item.vlanid}}"
    state: merged
  loop: "{{access_port}}"
  when: inventory_hostname == "AccessSwitches"

- name: Configure Trunk Port
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{item}}"
        mode: trunk
        trunk:
          encapsulation: dot1q
          allowed_vlans: "{{ vlan_info | map(attribute='id') | list }}"
    state: merged
  loop: "{{trunk_port}}"