---
- name: Gather information about all interfaces
  hosts: CoreSw1
  gather_facts: false

  tasks:
  - name: Gather fact of interfaces Cisco
    cisco.ios.ios_facts:
      gather_subset: all
      gather_network_resources: l2_interfaces
    register: output
  - name: Create config files from template
    ansible.builtin.template:
      src: ~/MyGit/NetworkAutomation/Ansible/Templates/interfaces_templates.j2
      dest: ./Interfaces_Cfg/{{inventory_hostname}}_interfaces_config.txt
