---
- name: Gather information about all interfaces
  hosts: CoreSw1
  gather_facts: false

  tasks:
  - name: Gather fact of interfaces Cisco
    cisco.ios.ios_facts:
      gather_subset: all
      gather_network_resources: l2_interfaces
    register: output
  - name: Create config files from template
    ansible.builtin.template:
      src: interface_template.j2
      dest: Ansible/Interfaces/Interfaces_Cfg/{{ inventory_hostname }}_interfaces_cfg.txt
