---

- name: Get information all interfaces of Cisco device
  hosts: all
  gather_facts: false

  tasks:
  - name: Thu thập thông tin tất các cổng trên thiết bị Cisco
    cisco.ios.ios_facts:
      gather_subset:
        - interfaces
    register: output
  - name: Tạo file theo template
    ansible.builtin.template:
      src: /home/user/MyGit/NetworkAutomation/Ansible/templates/interfaces_templates.j2
      dest: ./Interfaces_l2/{{inventory_hostname}}_interfaces.txt

