---
- name: SMNP Config
  hosts: all
  gather_facts: false

  tasks:
  - name: Config following command lines
    cisco.ios.ios_config:
      lines:
        - snmp-server community quan ro
        - snmp-server enable traps snmp
        - snmp-server host {{smnp_ip_server}} version 2c quan udp-port 161