---
- name: SNMP Config
  cisco.ios.ios_config:
    lines:
      - snmp-server community {{community}} ro
      - snmp-server enable traps snmp
      - snmp-server host {{snmp_ip_server}} version 2c {{community}} udp-port 161
