---
- name: Config port edge
  cisco.ios.ios_config:
    lines:
      - spanning-tree bpduguard enable
      - spanning-tree portfast edge
    parents: "{{access_port}}"

- name: Config root switch
  cisco.ios.ios_config:
    lines:
      - spanning-tree vlan "{{root_vlan}}"" root primary
      - spanning-tree vlan "{{secondary_vlan}}"" root secondary
    delegate_to: "{{root_sw}}"