---
- name: Config port edge
  cisco.ios.ios_config:
    lines:
      - spanning-tree bpduguard enable
      - spanning-tree portfast edge
    parents: interface {{item.name}}
  loop: "{{access_port}}"
  when: inventory_hostname | regex_search('^Access.*$')

- name: Config root switch
  cisco.ios.ios_config:
    lines:
      - spanning-tree vlan {{item.root_vlan}} root primary
      - spanning-tree vlan {{item.secondary_vlan}} root secondary
  loop: "{{STP_root}}"
  when: inventory_hostname == item.device