---
- name: Config VRRP
  gather_facts: false
  hosts: CoreSw2
  tasks:
  - name: Config VRRP 1
    cisco.ios.ios_config:
      lines:
        - no shut
        - vrrp 1 ip 192.168.10.3
        - vrrp 1 preempt
      parents: interface vlan10    
  - name: Config VRRP 3
    cisco.ios.ios_config:
      lines:
        - no shut
        - vrrp 3 ip 192.168.30.3
        - vrrp 3 preempt
      parents: interface vlan30  
  - name: Config VRRP 6
    cisco.ios.ios_config:
      lines:
        - no shut
        - vrrp 6 ip 192.168.60.3
        - vrrp 6 preempt
      parents: interface vlan60
  - name: Config VRRP 2
    cisco.ios.ios_config:
      lines:
        - no shut
        - vrrp 2 ip 192.168.20.3
        - vrrp 2 priority 110
        - vrrp 2 preempt
      parents: interface vlan20  
  - name: Config VRRP 4
    cisco.ios.ios_config:
      lines:
        - no shut
        - vrrp 4 ip 192.168.40.3
        - vrrp 4 priority 110
        - vrrp 4 preempt
      parents: interface vlan40
