---
- name: Access Port Config
  hosts: AccessSw1
  gather_facts: false

  vars:
    access_port:
      - { name: "Ethernet1/0" , vlanid: "60" }
      - { name: "Ethernet1/1" , vlanid: "20" }
      - { name: "Ethernet1/2" , vlanid: "30" }
      - { name: "Ethernet1/3" , vlanid: "40" }
  tasks:
    - name: Configure Access Port
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{item.name}}"
            mode: access
            access:
              vlan: "{{item.vlanid}}"
        state: merged
      loop: "{{access_port}}"
