---
- name: OSPF Config
  hosts: Routers
  gather_facts: false

  tasks:
  - name: OSPF Config process 1 for Routers
    cisco.ios.ios_config:
      lines:
        - network 192.168.0.0 0.0.255.255 area 0
        - passive-interface e1/0
        - default-information originate metric-type 1
      parents:
        - router ospf 1
