---

- name: Get information all interfaces of Cisco device
  hosts: Switches
  gather_facts: false

  tasks:
  - name: Thu thập thông tin tất các cổng trên thiết bị Cisco
    cisco.ios.ios_facts:
      gather_subset:
      - interfaces
    register: output
  - name: In ra
    ansible.builtin.debug:
      msg: "{{ output }}"

