---
CoreSwitches:
  hosts:
    CoreSw1:
      ansible_host: 192.168.60.1
    CoreSw2:
      ansible_host: 192.168.60.2

AccessSwitches:
  hosts:
    AccessSw1:
      ansible_host: 192.168.60.5
    AccessSw2:
      ansible_host: 192.168.60.6
    AccessSw3:
      ansible_host: 192.168.60.7

ServerSwitch:
  hosts:
    ServerSw:
      ansible_host: 192.168.60.8
Switches:
  children:
    CoreSwitches:
    AccessSwitches:
    ServerSwitch:
  vars:
    ansible_user: root
    ansible_ssh_pass: quan
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

Routers:
  hosts:
    R1:
      ansible_host: 192.168.200.2
    R2:
      ansible_host: 192.168.200.6
  vars:
    ansible_user: root
    ansible_ssh_pass: quan
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

NetworkDevices:
  children:
    Switches:
    Routers:
