---
- name: Cisco show version example
  hosts: all
  gather_facts: false

  tasks:

  - name: Gather only the config and default facts
    cisco.ios.ios_facts:
      gather_subset:
      - config

  - name: Show facts
    debug:
      msg: "{{ ansible_facts.net_version }}"
