- name: Config interfaces_l3 CoreSwitches
  hosts: CoreSw1
  gather_facts: false

  tasks:
  - name: Config l3_interfaces "vlan 10 192.168.10.1/24" for CoreSw1
    cisco.ios.ios_l3_interfaces:
      config:
        - name: vlan 10
          ipv4:
            - address: 192.168.10.1/24
        - name: vlan 20
          ipv4:
            - address: 192.168.20.1/24
        - name: vlan 30
          ipv4:
            - address: 192.168.30.1/24
        - name: vlan 40
          ipv4:
            - address: 192.168.40.1/24
        - name: e0/0
          ipv4:
            - address: 192.168.200.1/30
        - name: port-channel5
          ipv4:
            - address: 192.168.200.9/30
      state: merged
  