- name: Config interfaces_l3
  hosts: R1
  gather_facts: false

  tasks:
  - name: Config l3_interfaces
    cisco.ios.ios_l3_interfaces:
      config:
        - name: e1/1
          ipv4:
            - address: 192.168.200.2/30
        - name: e1/0
          ipv4:
            - dhcp:
                enable: true
      state: merged

