---
- name: Trunking config for CoreSwitch
  hosts: CoreSwitches
  gather_facts: false
  
  tasks:
  - name: Config for l2_interfaces port-channel1 mode trunk, trunking encapsulation dot1q, trunking allowed vlans
    cisco.ios.ios_l2_interfaces:
      config:
        - name: port-channel1
          mode: trunk
          trunk:
            encapsulation: dot1q
            allowed_vlans: all

  


